ALTER TYPE "PropertyDocumentType" ADD VALUE 'EDITAL';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'ANUNCIO_CAIXA';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'MATRICULA';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'CERTIDAO_MATRICULA';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'TERMO_ARREMATACAO';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'COMPROVANTE_PAGAMENTO';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'COMPROVANTE_FGTS';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'CONTRATO_CAIXA';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'ITBI';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'COMPROVANTE_ITBI';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'PROTOCOLO_CARTORIO';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'REGISTRO_IMOVEL';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'MATRICULA_ATUALIZADA';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'IPTU';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'CONDOMINIO';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'VISTORIA';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'ORCAMENTO';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'NOTA_FISCAL';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'FOTO';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'CONTRATO_VENDA';
ALTER TYPE "PropertyDocumentType" ADD VALUE 'OUTRO';

ALTER TYPE "PropertyDocumentStatus" ADD VALUE 'RECEIVED';
ALTER TYPE "PropertyDocumentStatus" ADD VALUE 'VALIDATED';
ALTER TYPE "PropertyDocumentStatus" ADD VALUE 'CANCELLED';
ALTER TYPE "PropertyDocumentStatus" ADD VALUE 'PENDENTE';
ALTER TYPE "PropertyDocumentStatus" ADD VALUE 'RECEBIDO';
ALTER TYPE "PropertyDocumentStatus" ADD VALUE 'VALIDADO';
ALTER TYPE "PropertyDocumentStatus" ADD VALUE 'VENCIDO';
ALTER TYPE "PropertyDocumentStatus" ADD VALUE 'CANCELADO';

ALTER TABLE "property_documents"
ADD COLUMN "file_name" TEXT,
ADD COLUMN "mime_type" TEXT,
ADD COLUMN "file_size" INTEGER,
ADD COLUMN "document_date" TIMESTAMP(3),
ADD COLUMN "uploaded_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;